- Dockerfile
The last 3 lines (commented) are the docker commands to run to build and run the images needed
> Add Dockerfile for GCpedia

- config.php
Followed instructions here:
https://www.mediawiki.org/wiki/Manual:LocalSettings.php#Setting_copyright_for_the_site
Not sure how to handle French version of the site.  Legal code is available in English and French
https://creativecommons.org/licenses/by/4.0/legalcode
https://creativecommons.org/licenses/by/4.0/legalcode.fr
> Add Creative Commons Attribution 4.0 International

- extensions/mwSimpleSamlAuth/SimpleSamlAuth.class.php
adding lang to relay state of saml so it can be parsed on gcconnex side
> pass lang as part of relaystate

- skins/Vector/VectorTemplate.php
> remove stats from sidebar

- extensions/CrawlerSpecials/.gitignore
- extensions/CrawlerSpecials/SpecialSearchListUsers.php
- extensions/CrawlerSpecials/extension.json
> added mod for search crawler friendly versions of list pages

- config.php
Remove option to upload flash file on wiki
https://zube.io/tbs-sct/gctools/c/5601
> remove flash file

- .bicep/wiki-dev.bicep
- docker/LocalSettings.php.docker
Azure is phasing out their managed mariadb service so switching this to the one they're not getting rid of.
> Update wiki-dev.bicep to use mysql flexible server

- .gitmodules
- Dockerfile
- config-gcpedia.php
- docker-compose.yml
> add TimedMediaHandler for embedding uploaded media files

- extensions/SkinTweaksGCpedia/extension.json
- extensions/SkinTweaksGCpedia/i18n/en.json
- extensions/SkinTweaksGCpedia/i18n/fr.json
- extensions/SkinTweaksGCpedia/resources/js/newUserPage.js
from #187
updated to check for presence of deleted revisions too.
closes #187
> adding a js script for gcpedia to replace new user page functionality

- extensions/SkinTweaksGCpedia/i18n/en.json
- extensions/SkinTweaksGCpedia/i18n/fr.json
- extensions/SkinTweaksGCpedia/resources/js/skintweaksgcpedia.js
needed dues to the changes to how the setlang parameter works.
fixes #201
> fix for the gcpedia header language toggle

- .bicep/PR/wiki-test-instance.bicep
- .bicep/wiki-dev.bicep
- docker-compose.yml
- docker/LocalSettings.php.docker
Specifically in azure web apps and similar managed environments or containers we don't fully control.
> update settings env vars to something less likely to be used for something else

- extensions/GCUserCreateForm/i18n/en.json
change awknowledge to acknowledge for signup form
> change awknowledge to acknowledge

- .azure/dev-setup.sh
- .azure/env-init.sh
- .azure/nginx.config
- config-gcpedia.php
- maintenance/dockerInstall.php
For now just enough to get it running, any optimization to follow separately
closes #202
> config and init scripts for azure web app php environment

- .azure/env-init.sh
- .bicep/PR/test-instance-setup.bicep
- .bicep/PR/wiki-test-instance.bicep
- azure-pipelines-PR.yaml
> run gcpedia pr instance in azure web app php environment

- .azure/nginx.config
now that it's working, it can be more properly polished, some references used:
https://www.nginx.com/resources/wiki/start/topics/recipes/mediawiki/
https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
https://www.mediawiki.org/wiki/Manual:Short_URL/Nginx
closes #203
> Update, some basic hardening for nginx config

- .gitmodules
- Dockerfile
- azure-pipelines-PR.yaml
- config-gcpedia.php
- docker-compose.yml
- docker/LocalSettings.php.docker
> Add Widgets extension

- azure-pipelines-sync.yaml
Mirror the repo into azure devops, ideally this would use something less tied to a user than a PAT but that's all I have right now.
closes #228
> Create sync pipeline

- azure-pipelines-deploy.yaml
same as the PR code deployment but with build and deploy split into separate jobs to run in different pools
closes #231
> gcpedia code deploy to azure web app pipeline

- maintenance/pipelines/azp-db-import.yaml
fetch credentials from key vault then use them for the import.
closes #235
> pipeline file for importing a db dump

- pipelines/deploy_mediawiki_version.yaml
To be used for intermediate db updates.
> Create a pipeline to deploy a specific version of mediawiki to azure webapp

- Dockerfile
needed for https://www.mediawiki.org/wiki/Extension:PdfBook
> Dockerfile was missing htmldoc install

- .bicep/PR/wiki-test-instance.bicep
- init/init.sh
* Init script: run maintenance scripts through run.php
> Various attempts to get the PR instance init and install working again

- site/config-gcwiki.php
Defaults to openid being off if not fully configured.
closes #262
> openid extension config from env

- haibun/e2e/features/extensions/multilang.feature
Seems to get stuck on the the first edit popup.
> fix multilang haibun test

- azure-pipelines-sync.yaml
this should allow prune to work, might also work from the start with an empty mirror repo.
> Try a slightly different sync approach
